// src/components/NavMenu/NavMenu.tsx
'use client';
import styled from '@emotion/styled';
import useMenuStore from '../../stores/MenuStore';
import Loader from '../Loader/Loader';
import { emitRouteChange } from './../../events/routerEvents';

import { playToneAtRoute } from '../../audio';
import { SlideInRoute, routes } from './../../slideInRoutes';

const Container = styled.div`
  position: fixed;
  right: 0;
  left: 0;
  top: 0;
  z-index: 1;
  margin: 0;
  nav {
    height: 4rem;
    display: grid;
    grid-template-columns: 3fr 1fr 1fr 1fr;
    width: var(--content-width);
    margin: 0 auto;
    &:hover {
      cursor: pointer;
    }
    @media (max-width: 1350px) {
    }
    @media (max-width: 850px) {
      grid-template-columns: 1fr 1fr;
    }
  }

  .item {
    text-decoration: none;
    font-weight: 400;
    font-size: 1rem;
    font-family: var(--font-serif);
    background: none;
    border: 0;
    color: inherit;
    display: flex;
    cursor: pointer;
    align-items: center;
    transition: all 0.2s ease-in;
    span {
      margin-left: 0;
      padding: 0.5rem 2rem;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      padding: 0 2rem;
      border-radius: 2rem;
      background: rgba(255, 255, 255, 0.0001);
      backdrop-filter: blur(10px);
      height: 2rem;
    }
    &--home {
      padding: 0 2rem;
      span {
        display: block;
        width: 2rem;
        height: 2rem;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        padding: 0;
        border-radius: 2rem;
        background: rgba(255, 255, 255, 0.0001);
        backdrop-filter: blur(10px);
      }
      &.active span,
      &:hover span {
        background: var(--primary);

        letter-spacing: normal;
      }
    }

    &.active,
    &:hover {
      color: var(--secondary);
      span {
        background: rgba(255, 255, 255, 0.11);
        backdrop-filter: blur(10px);
      }
      /* letter-spacing: 0.2rem; */
    }
  }
`;

const navItems = [routes.PROJECTS, routes.EXPERIENCES, routes.RESUME];

const NavMenu = () => {
  const { activeMenuItem, setActiveMenuItem } = useMenuStore();

  const navigateTo = (to: SlideInRoute) => {
    if (activeMenuItem.key === to.key) {
      playToneAtRoute();
    } else {
      playToneAtRoute(to.key);
      emitRouteChange({ to });
      setActiveMenuItem(to);
    }
  };

  return (
    <Container>
      <nav>
        <button
          onClick={() => navigateTo(routes.HOME)}
          className={`item item--home ${
            activeMenuItem.key === routes.HOME.key ? 'active' : ''
          }`}>
          <Loader />
        </button>
        {navItems.map((route) => (
          <button
            onClick={() => navigateTo(route)}
            key={route.key}
            className={`item ${
              activeMenuItem.key === route.key ? 'active' : ''
            }`}>
            <span>{route.label}</span>
          </button>
        ))}
      </nav>
    </Container>
  );
};

export default NavMenu;

// src/lib/components/NavMenu/NavMenu.svelte
<script lang="ts">
	import { page } from '$app/stores';

	import { base } from '$app/paths';
	import { navItems } from '$lib/params';

	let currentRoute = '/';

	$: {
		if ($page) {
			currentRoute = $page.url.pathname;

			console.log(currentRoute);
		}
	}
</script>

<div class="nav-menu">
	<nav>
		<a
			class="nav-menu-item nav-menu-item--home"
			class:active={currentRoute === '/'}
			href={`${base}/`}
		>
			<span>/</span>
		</a>
		{#each navItems as item}
			<a
				href={`${base}${item.route}`}
				class="nav-menu-item"
				class:active={currentRoute === item.route}
			>
				<span>{item.title}</span>
			</a>
		{/each}
	</nav>
</div>

<style lang="scss">
	.nav-menu {
		position: fixed;
		right: 0;
		left: 0;
		top: 0;
		z-index: 100000;
		margin: 0;
		nav {
			height: 4rem;
			display: grid;
			grid-template-columns: 3fr 1fr 1fr 1fr;
			&:hover {
				cursor: pointer;
			}
			@media (max-width: 1350px) {
			}
			@media (max-width: 850px) {
				grid-template-columns: 1fr 1fr;
			}
		}

		&-item {
			text-decoration: none;
			font-weight: 400;
			font-family: var(--font-serif);

			border-radius: 2rem;
			border: 0;

			color: inherit;
			display: flex;
			align-items: center;
			transition: all 0.2s ease-in;

			span {
				margin-left: 0;
				padding: 0.5rem 2rem;
				display: inline-flex;
				align-items: center;
				justify-content: center;
				padding: 0 2rem;
				border-radius: 2rem;
				background: rgba(255, 255, 255, 0.0001);
				backdrop-filter: blur(10px);
				height: 2rem;
			}
			&--home.nav-menu-item {
				padding: 0 2rem;
				span {
					display: block;
					width: 2rem;
					height: 2rem;
					display: inline-flex;
					align-items: center;
					justify-content: center;
					padding: 0;
					border-radius: 2rem;
					background: rgba(255, 255, 255, 0.0001);
					backdrop-filter: blur(10px);
				}
				&.active span,
				&:hover span {
					background: var(--primary);

					letter-spacing: normal;
				}
			}

			&.active,
			&:hover {
				color: var(--secondary);
				letter-spacing: 0.2rem;
			}
		}
	}
</style>
