// src/lib/components/SkillsGrid/SkillItem.svelte
<script lang="ts">
	export let skill: any;
	export let textOnly: boolean;
</script>

<div class="font-mono {textOnly ? 'textOnly' : ''}">
	{#if skill.data.logo.url}
		<img src={skill.data.logo.url} alt={skill.data.logo.alt} class="w-full" />
	{:else}
		{skill.data.name}
	{/if}
</div>

<style lang="scss">
	div {
		display: flex;
		padding: 0 var(--grid-padding);
		flex-direction: column;
		&.textOnly {
			display: inline;
		}
	}
	img {
		margin-bottom: 1rem;
	}
</style>

// src/components/Common/Skills/SkillItem.jsx
import styled from '@emotion/styled';
import clsx from 'clsx';

const Container = styled.div`
  display: flex;
  padding: 0 var(--grid-padding);
  flex-direction: column;
  &.textOnly {
    display: inline;
  }
  img {
    margin-bottom: 1rem;
    max-width: 100%;
  }
`;

const SkillItem = ({ skill, textOnly }) => {
  if (!skill) return <></>;
  return (
    <Container className={clsx({ textOnly: textOnly })}>
      {skill.logo.url ? (
        <img
          src={skill.logo.url}
          alt={skill.logo.alt}
        />
      ) : (
        skill.name
      )}
    </Container>
  );
};

export default SkillItem;
